-- Supabase auth scaffolding for EIH Digital

create extension if not exists pgcrypto;

drop table if exists public.allowed_users;

create table if not exists public.specialties (
  id uuid primary key default gen_random_uuid(),
  name text unique not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users on delete cascade,
  email text,
  full_name text,
  specialty_id uuid references public.specialties on delete set null,
  must_change_password boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.roles (
  id bigint generated by default as identity primary key,
  name text unique not null,
  created_at timestamptz not null default now()
);

create table if not exists public.user_roles (
  user_id uuid references auth.users on delete cascade,
  role_id bigint references public.roles on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, role_id)
);

create index if not exists user_roles_user_id_idx on public.user_roles (user_id);
create index if not exists user_roles_role_id_idx on public.user_roles (role_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_specialties_updated_at on public.specialties;
create trigger set_specialties_updated_at
before update on public.specialties
for each row execute procedure public.set_updated_at();

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row execute procedure public.set_updated_at();

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    where ur.user_id = auth.uid()
      and r.name = 'admin'
  );
$$;

create or replace function public.has_role(role_name text)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    where ur.user_id = auth.uid()
      and r.name = role_name
  );
$$;

create or replace function public.has_any_role(role_names text[])
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    where ur.user_id = auth.uid()
      and r.name = any(role_names)
  );
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

alter table public.specialties enable row level security;
alter table public.profiles enable row level security;
alter table public.roles enable row level security;
alter table public.user_roles enable row level security;

create policy "Specialties: read all"
  on public.specialties
  for select
  using (auth.uid() is not null);

create policy "Specialties: admin manage"
  on public.specialties
  for all
  using (public.is_admin())
  with check (public.is_admin());

create policy "Profiles: read own"
  on public.profiles
  for select
  using (auth.uid() = id);

create policy "Profiles: update own"
  on public.profiles
  for update
  using (auth.uid() = id);

create policy "Profiles: admin manage"
  on public.profiles
  for all
  using (public.is_admin())
  with check (public.is_admin());

create policy "Roles: read all"
  on public.roles
  for select
  using (auth.uid() is not null);

create policy "Roles: admin manage"
  on public.roles
  for all
  using (public.is_admin())
  with check (public.is_admin());

create policy "User roles: read own"
  on public.user_roles
  for select
  using (auth.uid() = user_id);

create policy "User roles: admin manage"
  on public.user_roles
  for all
  using (public.is_admin())
  with check (public.is_admin());

insert into public.roles (name)
values ('admin'), ('doctor'), ('assistant'), ('nurse'), ('allied')
on conflict (name) do nothing;
